apiVersion: 1

datasources:
  - name: MySQL
    uid: bg0evlngt9o8we
    type: mysql
    access: proxy
    url: mysql:3306
    user: grafana
    jsonData:
      database: ${DB_NAME}
    secureJsonData:
      password: grafana_ro
    editable: true
